import "./globals.css";
import Header from "./Components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// it creates the structure of our website. and all of our pages calls here in this layout file through children prop.
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
